<?php 
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

add_action('customize_register', 'bco_customize_register');
function bco_customize_register($wp_customize) {

	# Logo panel
	$wp_customize->add_section( 'section-logo' , array(
		'title' => __( 'Logo', 'bco' ),
		'priority' => 30
	));

	$wp_customize->add_setting( 'company-logo', array('type' => 'option') );
	$wp_customize->add_control( new WP_Customize_Image_Control( $wp_customize, 'company-logo', array(
		'label' => __( 'Upload Logo', 'bco' ),
		'section' => 'section-logo',
		'settings' => 'company-logo',
		'description' => 'Your main company logo for the website.',
		'priority' => 100
	))); 

	# Company info panel
	$wp_customize->add_section( 'website-settings' , array(
		'title' => __( 'Website Settings', 'bco' ),
		'priority' => 30
	));

	$wp_customize->add_setting('fallback-image', array('type' => 'option'));
	$wp_customize->add_control( new WP_Customize_Image_Control( $wp_customize, 'fallback-image', array(
		'label' => 'Fallback Image',
		'section' => 'website-settings',
		'settings' => 'fallback-image',
	))); 

	# Company info panel
	$wp_customize->add_section( 'section-company' , array(
		'title' => __( 'Company Info', 'bco' ),
		'priority' => 30
	));

	$wp_customize->add_setting( 'company-title', array('type' => 'option') );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'company-title', array(
		'label' => __( 'Company Title', 'bco' ),
		'section' => 'section-company',
		'settings' => 'company-title'
	))); 

	$wp_customize->add_setting( 'company-address', array('type' => 'option') );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'company-address', array(
		'label' => __( 'Company Address', 'bco' ),
		'section' => 'section-company',
		'settings' => 'company-address'
	))); 

	$wp_customize->add_setting( 'company-location', array('type' => 'option') );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'company-location', array(
		'label' => __( 'Company Location', 'bco' ),
		'section' => 'section-company',
		'settings' => 'company-location'
	))); 

	$wp_customize->add_setting( 'company-phone', array('type' => 'option') );	
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'company-phone', array(
		'label' => __( 'Company Phone Number', 'bco' ),
		'section' => 'section-company',
		'settings' => 'company-phone'
	))); 

	$wp_customize->add_setting( 'company-email', array('type' => 'option') );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'company-email', array(
		'label' => __( 'Company Email Address', 'bco' ),
		'section' => 'section-company',
		'settings' => 'company-email'
	))); 

	# Social media panel
	$wp_customize->add_section( 'section-social-media' , array(
		'title' => __( 'Social Media', 'bco' ),
		'priority' => 30,
		'description' => __( '<div class="error" style="padding:8px;"><strong>Important!</strong> Must use "http://" before links.</div>', 'bco' )
	));

	$wp_customize->add_setting( 'facebook-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'facebook-link', array(
		'label' => __( 'Facebook URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'facebook-link'
	))); 
	
	$wp_customize->add_setting( 'twitter-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'twitter-link', array(
		'label' => __( 'Twitter URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'twitter-link'
	))); 
	
	$wp_customize->add_setting( 'google-plus-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'google-plus-link', array(
		'label' => __( 'Google Plus URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'google-plus-link'
	))); 
	
	$wp_customize->add_setting( 'linkedin-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'linkedin-link', array(
		'label' => __( 'LinkedIn URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'linkedin-link'
	))); 
	
	$wp_customize->add_setting( 'pinterest-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'pinterest-link', array(
		'label' => __( 'Pinterest URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'pinterest-link'
	))); 
	
	$wp_customize->add_setting( 'instagram-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'instagram-link', array(
		'label' => __( 'Instagram URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'instagram-link'
	)));
	
	$wp_customize->add_setting( 'youtube-link', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'youtube-link', array(
		'label' => __( 'Youtube URL', 'bco' ),
		'section' => 'section-social-media',
		'settings' => 'youtube-link'
	)));

	# Analytics panel
	$wp_customize->add_section( 'section-analytics' , array(
		'title' => __( 'Analytics', 'bco' ),
		'priority' => 30
	));

	$wp_customize->add_setting( 'google-analytics-id', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'google-analytics-id', array(
		'label' => __( 'Google Analytics UA-XXXXX-X ID', 'bco' ),
		'section' => 'section-analytics',
		'settings' => 'google-analytics-id',
		'priority' => 20
	))); 

	# Developer panel
	$wp_customize->add_section( 'section-advanced' , array(
		'title' => __( 'Developers', 'bco' ),
		'priority' => 30
	));

	$wp_customize->add_setting( 'bco-dev-warnings', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'bco-dev-warnings', array(
		'label' => __( 'Hide developer messages', 'bco' ),
		'section' => 'section-advanced',
		'settings' => 'bco-dev-warnings',
		'type' => 'checkbox',
		'priority' => 20
	))); 

	$wp_customize->add_setting( 'development-environment', array( 'type' => 'option' ) );
	$wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'development-environment', array(
		'label' => __( 'Development Environment', 'bco' ),
		'section' => 'section-advanced',
		'settings' => 'development-environment',
		'type' => 'select',
		'choices' => array(
			'local' => 'Local',
			'beta' => 'Beta',
			'live' => 'Live'
		),
		'priority' => 20
	))); 
}














