<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

# Google analytics
add_action('wp_footer', 'bco_google_analytics');
function bco_google_analytics() {
	$id = get_option('google-analytics-id');
	if ( $id ) {
		?>
			<script>
				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

				ga('create', '<?php echo $id; ?>', 'auto');
				ga('send', 'pageview');
			</script>
		<?php
	}
}