<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

# Get dev environment
function get_development_environment() {
	return get_option('development-environment');
}

# Show developer messages 
function show_developer_messages() {
	if ( (int) get_option('bco-dev-warnings') !== 1 ) {
		return true;
	} else {
		return false;
	}
}

function get_developer_options_link() {
	return get_admin_url() . 'customize.php?autofocus[section]=section-advanced';
}

# Admin bar status label
add_action('admin_bar_menu', 'admin_bar_dev_env');
function admin_bar_dev_env($admin_bar) {
	$env = get_development_environment();
	if ( $env === 'local' ) {
		$title = 'Status: Local Dev';
	} elseif ( $env === 'beta' ) {
		$title = 'Status: In Beta';
	} else {
		$title = 'Status: Live';
	}

	$admin_bar->add_menu( 
		array(
			'id' => 'bco-dev-env-' . $env,
			'parent' => 'top-secondary',
			'title' => $title,
			'href' => get_developer_options_link()
		) 
	);
}
