<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

# Note: 
# In child theme, use wp_dequeue_script to remove these scripts/styles
# and wp_enqueue_script scripts/styles from the child theme

add_action('wp_enqueue_scripts', 'frontend_scripts_and_styles');
add_action('admin_enqueue_scripts', 'backend_scripts_and_styles');

function frontend_scripts_and_styles() {
	# Scripts
	wp_enqueue_script('jquery' );
	wp_enqueue_script('bco-framework-theme-scripts', BCO_SCRIPTS_DIRECTORY . 'main.min.js', array('jquery'), null, true);

	# Styles
	wp_enqueue_style('bco-framework-theme-style', BCO_STYLESHEET_DIRECTORY . 'main.min.css');

	# Google Fonts
	// if ( defined('GOOGLE_FONTS') ) {
	// 	wp_register_style( 'bco-google-font', 'https://fonts.googleapis.com/css?family=' . GOOGLE_FONTS);
	// 	wp_enqueue_style( 'bco-google-font' );
	// }
}

function backend_scripts_and_styles() {
	wp_register_style( 'bco-admin-css', BCO_RESOURCES_DIRECTORY . 'admin/admin.css' );
	wp_enqueue_style( 'bco-admin-css' );
	wp_enqueue_script( 'bco-admin-js', BCO_RESOURCES_DIRECTORY . 'admin/admin.js', array(), null, true );
}