<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

# Global constants
define('BCO_FRAMEWORK_DIRECTORY_NAME', 'starter2017');
define('BCO_BASE_DIRECTORY', get_template_directory());
define('BCO_CONFIG_DIRECTORY', get_template_directory() . '/config/');
define('BCO_RESOURCES_DIRECTORY', get_template_directory_uri() . '/resources/');
define('BCO_IMAGE_DIRECTORY', get_template_directory() . '/resources/images/');
define('BCO_STYLESHEET_DIRECTORY', get_template_directory_uri() . '/resources/styles/css/');
define('BCO_SCRIPTS_DIRECTORY', get_template_directory_uri() . '/resources/scripts/');

# Required files
require BCO_CONFIG_DIRECTORY . '/config.php';
