<?php 
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

function get_development_environment() {
	return ((int) get_option('development-environment') === 1 ? 'local' : 'live';
}