<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

/** 
 * Get icon 
 */
function get_icon($icon = 'link.svg') {

	// Get file
	$file = BCO_IMAGE_DIRECTORY . 'svg/' . $icon;

	// Return
	if ( file_exists($file) ) {
		return file_get_contents(BCO_IMAGE_DIRECTORY . 'svg/' . $icon); 
	
	// Error
	} else {
		return 'This is not the icon you are looking for (' . $icon . ')';
	}
}

/**
 * Get post excerpt
 */
function get_post_excerpt($args = array()) {

	// Get defaults
	$word_count = (array_key_exists('word_count', $args)) ? $args['word_count'] : 30;
	$post_id = (array_key_exists('post_id', $args)) ? $args['post_id'] : get_the_ID();
	$read_more_text = (array_key_exists('read_more_text', $args)) ? $args['read_more_text'] : 'Continue reading...';
	$link = (array_key_exists('link', $args)) ? $args['link'] : true;

	// Get read more link
	$read_more_text = ($read_more_text) ? $read_more_text : '';
	$read_more_link = ($link === true) ? ' <a href="' . get_permalink() . '" class="read-more-text">' . $read_more_text . '</a>' : '<span class="read-more-text">' . $read_more_text . '</span>';

	// Get content
	$content = get_post_field('post_content', $post_id);

	// Trim down
	$trimmed_content = wp_trim_words($content, $word_count, '') . $read_more_link;

	// Return
	return wpautop(strip_shortcodes($trimmed_content));
}

/** 
 * Navigation 
 * Flat menu: depth = -1;
 * Default: depth = 0;
 * Only first level: depth = 1;
 */
function get_navigation($args = array()) {

	// Get defaults
	$location = (array_key_exists('location', $args)) ? $args['location'] : 'primary';
	$depth = (array_key_exists('depth', $args)) ? $args['depth'] : 0;

	// Get menu
	if ( has_nav_menu($location) ) {
		wp_nav_menu( 
			array( 
				'theme_location' => $location,
				'container' => '',
				'items_wrap' => '%3$s',
				'depth' => $depth
			) 
		);
		return;

	// Error
	} else {
		echo '<code>Menu location does not exist: <strong>"' . $location . '"</strong></code>';
	}
}



















