<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

# Get icon
# TODO: fallback to link svg
function get_icon($icon) {
	if ( empty($icon) ) { return; }

	$file = BCO_IMAGE_DIRECTORY . 'svg/' . $icon;

	if ( file_exists($file) ) {
		return file_get_contents(BCO_IMAGE_DIRECTORY . 'svg/' . $icon); 
	} else {
		return 'This is not the icon you are looking for (' . $icon . ')';
	}
}

# Get post excerpt
function get_post_excerpt($args) {
		
	// Get defaults
	$word_count = (array_key_exists('word_count', $args)) ? $args['word_count'] : 30;
	$post_id = (array_key_exists('post_id', $args)) ? $args['post_id'] : get_the_ID();
	$read_more_text = (array_key_exists('read_more_text', $args)) ? $args['read_more_text'] : 'Continue reading...';
	$link = (array_key_exists('link', $args)) ? $args['link'] : true;

	// Get read more link
	$read_more_text = ($read_more_text) ? $read_more_text : '';
	$read_more_link = ($link === true) ? '<a href="' . get_permalink() . '" class="read-more-text"> ' . $read_more_text . '</a>' : '<span class="read-more-text">' . $read_more_text . '</span>';

	// Get content
	$content = get_post_field('post_content', $post_id);

	// Trim down
	$trimmed_content = wp_trim_words($content, $word_count, '') . $read_more_link;

	// Return
	return wpautop(strip_shortcodes($trimmed_content));
}

# Main navigation
function get_primary_navigation() {
	wp_nav_menu(
		array(
			'theme_location' => 'primary',
			'items_wrap' => '<ul id="primary-menu" class="primary-menu %2$s">%3$s</ul>',
			'container' => ''
		)
	);
}

# Mobile navigation
function get_mobile_navigation() {
	if ( has_nav_menu('mobile') ) {
		wp_nav_menu( 
			array( 
				'theme_location' => 'mobile',
				'container' => '',
				'items_wrap' => '%3$s'
			) 
		);
		return;

	} elseif ( has_nav_menu('primary') ) {
		wp_nav_menu( 
			array( 
				'theme_location' => 'primary',
				'container' => '',
				'items_wrap' => '%3$s'
			) 
		);
		return;

	}
}





















