<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

/** Setup */
require BCO_CONFIG_DIRECTORY . '/setup/modes.php';
require BCO_CONFIG_DIRECTORY . '/setup/theme-setup.php';
require BCO_CONFIG_DIRECTORY . '/setup/widgets.php';
require BCO_CONFIG_DIRECTORY . '/setup/customize-options.php';
require BCO_CONFIG_DIRECTORY . '/setup/scripts-styles.php';
require BCO_CONFIG_DIRECTORY . '/setup/cleanup.php';
require BCO_CONFIG_DIRECTORY . '/setup/gravity-forms.php';
require BCO_CONFIG_DIRECTORY . '/setup/google-analytics.php';
require BCO_CONFIG_DIRECTORY . '/setup/login-screen.php';
require BCO_CONFIG_DIRECTORY . '/setup/module-builder.php';

/** Functions */
require BCO_CONFIG_DIRECTORY . '/functions/website-info.php';
require BCO_CONFIG_DIRECTORY . '/functions/social-media.php';
require BCO_CONFIG_DIRECTORY . '/functions/helpers.php';
require BCO_CONFIG_DIRECTORY . '/functions/titles.php';

/** Admin files */
if ( is_admin() ) {
	require BCO_CONFIG_DIRECTORY . '/setup/theme-check.php';
}