<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

# Get icon
# TODO: fallback to link svg
function get_icon($icon) {
	if ( empty($icon) ) { return; }

	$file = BCO_IMAGE_DIRECTORY . 'svg/' . $icon;

	if ( file_exists($file) ) {
		return file_get_contents(BCO_IMAGE_DIRECTORY . 'svg/' . $icon); 
	} else {
		return 'This is not the icon you are looking for (' . $icon . ')';
	}
}

# Get post excerpt
function get_post_excerpt($word_count = 30, $post_id = null, $read_more_text = 'Continue reading...', $link = true) {
	// Get post id or default
	$post_id = ($post_id) ? $post_id : get_the_ID();

	// Get read more text
	$read_more_text = ($read_more_text) ? $read_more_text : '';

	// Link or not
	$read_more_link = ($link) ? ' <a href="' . get_permalink() . '" class="read-more-text"> ' . $read_more_text . '</a>' : ' <span class="read-more-text">' . $read_more_text . '</span>';

	// Get content and trim it down
	// and add the read more link
	$content = get_post_field('post_content', $post_id);
	$trimmed_content = wp_trim_words($content, $word_count, '') . $read_more_link;

	return wpautop(strip_shortcodes($trimmed_content));
}

# Main navigation
function get_primary_navigation() {
	wp_nav_menu(
		array(
			'theme_location' => 'primary',
			'items_wrap' => '<ul id="primary-menu" class="primary-menu %2$s">%3$s</ul>',
			'container' => ''
		)
	);
}

# Mobile navigation
function get_mobile_navigation() {
	if ( has_nav_menu('mobile') ) {
		wp_nav_menu( 
			array( 
				'theme_location' => 'mobile',
				'container' => '',
				'items_wrap' => '%3$s'
			) 
		);
		return;

	} elseif ( has_nav_menu('primary') ) {
		wp_nav_menu( 
			array( 
				'theme_location' => 'primary',
				'container' => '',
				'items_wrap' => '%3$s'
			) 
		);
		return;

	}
}





















