<?php
/**
 * @package BrandCo. Framework
 * Do not edit this file. Use a child theme.
 */

function get_social_media_links() {
	$links = array();
	$options[] = array(
		get_option('facebook-link'),
		get_option('twitter-link'),
		get_option('google-plus-link'),
		get_option('linkedin-link'),
		get_option('pinterest-link'),
		get_option('instagram-link'),
		get_option('youtube-link')
	);

	if ( get_option('facebook-link') ) { $links[] = array( 'title' => 'Facebook', 'link' => get_option('facebook-link'), 'icon' => get_icon('facebook.svg'), ); }
	if ( get_option('twitter-link') ) { $links[] = array( 'title' => 'Twitter', 'link' => get_option('twitter-link'), 'icon' => get_icon('twitter.svg'), ); }
	if ( get_option('google-plus-link') ) { $links[] = array( 'title' => 'Google Plus', 'link' => get_option('google-plus-link'), 'icon' => get_icon('google-plus.svg'), ); }
	if ( get_option('linkedin-link') ) { $links[] = array( 'title' => 'LinkedIn', 'link' => get_option('linkedin-link'), 'icon' => get_icon('linkedin.svg'), ); }
	if ( get_option('pinterest-link') ) { $links[] = array( 'title' => 'Pinterest', 'link' => get_option('pinterest-link'), 'icon' => get_icon('pinterest.svg'), ); }
	if ( get_option('instagram-link') ) { $links[] = array( 'title' => 'Instagram', 'link' => get_option('instagram-link'), 'icon' => get_icon('instagram.svg'), ); }
	if ( get_option('youtube-link') ) { $links[] = array( 'title' => 'YouTube', 'link' => get_option('youtube-link'), 'icon' => get_icon('youtube.svg'), ); }

	return $links;
}